# Generated by Django 3.1.6 on 2021-02-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='idRoom',
            field=models.CharField(default='3ywkeu8r', max_length=10, primary_key=True, serialize=False),
        ),
    ]
