# Generated by Django 3.1.6 on 2021-02-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20210223_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='idRoom',
            field=models.CharField(default='9vwaM4J2', max_length=10, primary_key=True, serialize=False),
        ),
    ]
