# Generated by Django 3.1.6 on 2021-02-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20210223_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='idRoom',
            field=models.CharField(default='3QmF4n4s', max_length=10, primary_key=True, serialize=False),
        ),
    ]
