# Generated by Django 3.1.6 on 2021-02-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20210223_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='idRoom',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
