# Generated by Django 3.1.6 on 2021-03-09 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_date_joined'),
        ('room', '0006_auto_20210309_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='userBanker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_banker', to='users.user'),
        ),
    ]
