# Generated by Django 3.1.6 on 2021-03-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
