# Generated by Django 3.1.6 on 2021-03-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210309_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/pictures/default.jpg', upload_to='media/pictures/'),
        ),
    ]
