# Generated by Django 3.1.6 on 2021-02-19 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_user_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('idTrType', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
            ],
            options={
                'db_table': 'TransactionType',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('idTransaction', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('concept', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('TnType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_tn_type', to='transaction.transactiontype')),
                ('userReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver', to='users.user')),
                ('userTransmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transmitter', to='users.user')),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
    ]
