# Generated by Django 3.1.6 on 2021-03-14 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='creationTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
