# Generated by Django 3.1.6 on 2021-03-15 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210313_2132'),
        ('transaction', '0002_transaction_creationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='userTransmitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_transmitter', to='users.user'),
        ),
    ]
