# Generated by Django 3.1.6 on 2021-03-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20210315_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='creationTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
