# Generated by Django 3.1.6 on 2021-03-24 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20210323_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='creationTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
